target_dir = "~/KSP"

[install]
base = "~/Downloads/ksp-linux-1.5.1.zip"
dlc1 = "~/Downloads/KSP-Making_History_Expansion-en-us-lin-1.5.1.zip"

[mods.adopted]
source_type = "adopted"
depends = ["KOS"]

[mods.ModuleManager]
source_type = "git"
source = "https://github.com/sarbian/ModuleManager.git"
branch = "master"

[mods.KOS]
source_type = "git"
source = "https://github.com/KSP-KOS/KOS.git"
branch = "master"
depends = ["ModuleManager"]

[mods.Kopernicus]
source_type = "git"
source = "https://github.com/Kopernicus/Kopernicus.git"
tag = "release-1.5.0-1"
enabled = true
patch = '''
--- a/src/Kopernicus/Constants/CompatibilityChecker.cs
+++ b/src/Kopernicus/Constants/CompatibilityChecker.cs
@@ -49,7 +49,7 @@ namespace Kopernicus
         // Compatible version
         internal const Int32 version_major = 1;
         internal const Int32 version_minor = 5;
-        internal const Int32 Revision = 0;
+        internal const Int32 Revision = 1;
         internal const Int32 Kopernicus = 1;
 
         public static Boolean IsCompatible()
'''

[mods.CustomBarnKit]
source_type = "git"
source = "https://github.com/sarbian/CustomBarnKit.git"

[mods.OPM]
source_type = "http"
source = "https://github.com/Galileo88/Outer-Planets-Mod/releases/download/${version}/Outer_Planets_Mod-${version}.zip"
version = "2.2.1"
depends = ["Kopernicus"]

[mods.PlanetaryBaseSystems]
source_type = "git"
source = "https://github.com/Nils277/KerbalPlanetaryBaseSystems.git"
enabled = false
depends = ["ModuleManager"]

[mods.B9PartSwitch]
source_type = "git"
source = "https://github.com/blowfishpro/B9PartSwitch.git"
depends = ["ModuleManager"]
enabled = false

[mods.NearFutureProps]
source_type = "git"
source="https://github.com/ChrisAdderley/NearFutureProps.git"
depends = ["ModuleManager"]
enabled = false

[mods.StationPartsExpansionRedux]
source_type = "git"
source = "https://github.com/ChrisAdderley/StationPartsExpansionRedux.git"
depends = ["ModuleManager", "B9PartSwitch", "NearFutureProps"]

[mods.KerbalAlarmClock]
source_type = "git"
source = "https://github.com/TriggerAu/KerbalAlarmClock.git"

[mods.KIS]
source_type = "git"
source = "https://github.com/ihsoft/KIS.git"
enabled = false

[mods.KAS]
source_type = "git"
source = "https://github.com/ihsoft/KAS.git"
enabled = false

[mods.DockRotate]
source_type = "git"
source = "https://github.com/peteletroll/DockRotate.git"
enabled = false

[mods.Konstruction]
source_type = "git"
source = "https://github.com/BobPalmer/Konstruction.git"
enabled = false
