target_dir = "~/KSP"

[install]
base = "~/Downloads/ksp-linux-1.5.1.zip"
dlc1 = "~/Downloads/KSP-Making_History_Expansion-en-us-lin-1.5.1.zip"

[mods.adopted]
source_type = "adopted"
depends = ["KOS"]

[mods.ModuleManager]
source_type = "git"
source = "https://github.com/sarbian/ModuleManager.git"
branch = "master"

[mods.KOS]
source_type = "git"
source = "https://github.com/KSP-KOS/KOS.git"
branch = "master"
depends = ["ModuleManager"]

[mods.Kopernicus]
source_type = "git"
source = "https://github.com/Kopernicus/Kopernicus.git"
tag = "release-1.5.0-1"
enabled = false

[mods.OPM]
source_type = "git"
source = "https://github.com/Galileo88/Outer-Planets-Mod.git"
depends = ["Kopernicus"]

[mods.PlanetaryBaseSystems]
source_type = "git"
source = "https://github.com/Nils277/KerbalPlanetaryBaseSystems.git"
enabled = false
depends = ["ModuleManager"]

[mods.B9PartSwitch]
source_type = "git"
source = "https://github.com/ChrisAdderley/StationPartsExpansionRedux.git"
depends = ["ModuleManager"]
enabled = false

[mods.NearFutureProps]
source_type = "git"
source="https://github.com/ChrisAdderley/NearFutureProps.git"

[mods.StationPartsExpansionRedux]
source_type = "git"
source = "https://github.com/ChrisAdderley/StationPartsExpansionRedux.git"
depends = ["ModuleManager", "B9PartSwitch", "NearFutureProps"]

[mods.KerbalAlarmClock]
source_type = "git"
source = "https://github.com/TriggerAu/KerbalAlarmClock.git"
enabled = false