target_dir = "~/KSP"

[install]
base = "~/Downloads/ksp-linux-1.5.1.zip"
dlc1 = "~/Downloads/KSP-Making_History_Expansion-en-us-lin-1.5.1.zip"

[mods.adopted]
source_type = "adopted"
depends = ["KOS"]

[mods.ModuleManager]
source_type = "git"
source = "https://github.com/sarbian/ModuleManager.git"
branch = "master"

[mods.KOS]
source_type = "git"
source = "https://github.com/KSP-KOS/KOS.git"
branch = "master"
depends = ["ModuleManager"]

[mods.Kopernicus]
source_type = "git"
source = "https://github.com/Kopernicus/Kopernicus.git"
tag = "release-1.5.1-1"
enabled = true

[mods.CustomBarnKit]
source_type = "git"
source = "https://github.com/sarbian/CustomBarnKit.git"

[mods.OPM]
source_type = "http"
source = "https://github.com/Galileo88/Outer-Planets-Mod/releases/download/${version}/Outer_Planets_Mod-${version}.zip"
version = "2.2.1"
depends = ["Kopernicus"]

[mods.KSPModFileLocalizer]
source_type = "git"
source = "https://github.com/Nils277/KSPModFileLocalizer.git"

[mods.PlanetaryBaseSystems]
source_type = "git"
source = "https://github.com/Nils277/KerbalPlanetaryBaseSystems.git"
enabled = true
depends = ["ModuleManager", "KSPModFileLocalizer"]

[mods.B9PartSwitch]
source_type = "git"
source = "https://github.com/blowfishpro/B9PartSwitch.git"
depends = ["ModuleManager"]
enabled = true

[mods.NearFutureProps]
source_type = "git"
source="https://github.com/ChrisAdderley/NearFutureProps.git"
depends = ["ModuleManager"]
enabled = true

[mods.StationPartsExpansionRedux]
source_type = "git"
source = "https://github.com/ChrisAdderley/StationPartsExpansionRedux.git"
depends = ["ModuleManager", "B9PartSwitch", "NearFutureProps"]

[mods.KerbalAlarmClock]
source_type = "git"
source = "https://github.com/TriggerAu/KerbalAlarmClock.git"

[mods.CommunityCategoryKit]
source_type = "git"
source = "https://github.com/BobPalmer/CommunityCategoryKit.git"

[mods.KSPDev]
source_type = "git"
source = "https://github.com/ihsoft/KSPDev.git"

[mods.KIS]
source_type = "git"
source = "https://github.com/ihsoft/KIS.git"
depends = ["CommunityCategoryKit", "KSPDev"]

[mods.KAS]
source_type = "git"
source = "https://github.com/ihsoft/KAS.git"
tag = "1.1"
depends = ["CommunityCategoryKit", "KSPDev"]

[mods.DockRotate]
source_type = "git"
source = "https://github.com/peteletroll/DockRotate.git"

[mods.KerbalEngineer]
source_type = "git"
source = "https://github.com/jrbudda/KerbalEngineer.git"

[mods.CommunityTechTree]
source_type = "git"
source = "https://github.com/ChrisAdderley/CommunityTechTree.git"

[mods.CommunityResourcePack]
source_type = "git"
source = "https://github.com/BobPalmer/CommunityResourcePack.git"

[mods.USITools]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries.git"

[mods.USI_LS]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/USI-LS.git"
depends = ["CommunityCategoryKit", "CommunityResourcePack", "USITools"]
patch = '''
--- a/Source/USILifeSupport/LifeSupportMonitor.cs
+++ b/Source/USILifeSupport/LifeSupportMonitor.cs
@@ -1,7 +1,6 @@
 ﻿using System;
 using System.CodeDom;
 using System.Collections.Generic;
-using System.Data.SqlTypes;
 using System.IO;
 using System.Linq;
 using System.Reflection;
'''

[mods.Konstruction]
source_type = "git"
source = "https://github.com/BobPalmer/Konstruction.git"
depends = ["CommunityResourcePack", "USITools"]

[mods.SCANsat]
source_type = "git"
source = "https://github.com/S-C-A-N/SCANsat.git"
branch = "release"

[mods.EnvironmentalVisualEnhancements]
source_type = "http"
source = "https://github.com/WazWaz/EnvironmentalVisualEnhancements/releases/download/EVE-1.4.2-2/EnvironmentalVisualEnhancements-1.4.2.2.zip"
enabled = false

[mods.StockVisualEnhancements]
source_type = "http"
source = "https://github.com/Galileo88/StockVisualEnhancements/releases/download/1.3.0.4/SVE.v1.3.0.4.zip"
enabled = false
depends = ["EnvironmentalVisualEnhancements"]

[mods.StockVisualEnhancements_HighRes]
source_type = "http"
source = "https://github.com/Galileo88/StockVisualEnhancements/releases/download/1.0.7/SVE_HighResTextures.zip"
enabled = false
depends = ["StockVisualEnhancements"]

[mods.scatterer]
source_type = "http"
source = "https://github.com/LGhassen/Scatterer/releases/download/0.0331b/scatterer-v0.0331b.zip"
enabled = false

[mods.X_Science]
source_type = "git"
source = "https://github.com/thewebbooth/KSP-X-Science.git"
patch = '''
--- a/X-Science/ScienceChecklistAddon.cs
+++ b/X-Science/ScienceChecklistAddon.cs
@@ -802,8 +802,8 @@ private bool UiActive( )
 
 		private void HammerMusicMute( )
 		{
-			if( muted )
-				 MusicLogic.SetVolume( 0f );
+//			if( muted )
+//				 MusicLogic.SetVolume( 0f );
 		}
 
 
@@ -835,14 +835,14 @@ public bool Muted
                     oldVolume = GameSettings.MUSIC_VOLUME;
 
                     // Mute the music
-                    MusicLogic.SetVolume(0f);
+//                    MusicLogic.SetVolume(0f);
  //                   _logger.Info("[MusicMute]: Muted music");
                 }
                 // Unmute
                 else
                 {
                     // Set the music volume to what it was before
-                    MusicLogic.SetVolume(oldVolume);
+//                    MusicLogic.SetVolume(oldVolume);
  //                   _logger.Info("[MusicMute]: Set music volume to: " + oldVolume);
                 }
 
'''

[mods.ClickThroughBlocker]
source_type = "git"
source = "https://github.com/linuxgurugamer/ClickThroughBlocker.git"

[mods.ToolbarControl]
source_type = "git"
source = "https://github.com/linuxgurugamer/ToolbarControl.git"
depends = ["ClickThroughBlocker"]

[mods.KronalVesselViewer]
source_type = "git"
source = "https://github.com/linuxgurugamer/KronalVesselViewer.git"
depends = ["ClickThroughBlocker", "ToolbarControl", "KAS"]
patch = '''
--- a/KronalVesselViewer/VesselViewConfig.cs
+++ b/KronalVesselViewer/VesselViewConfig.cs
@@ -1,14 +1,10 @@
 ﻿
-#define KERAMZIT
-#define KAS
-
 using System;
 using System.Collections.Generic;
 using System.Reflection;
 using System.Linq;
 using System.Text;
 using UnityEngine;
-using KAS;
 
 using ProceduralFairings;
 '''

[mods.IndicatorLights]
source_type = "git"
source = "https://github.com/KSPSnark/IndicatorLights.git"
depends = ["ModuleManager"]

[mods.AT_Utils]
source_type = "git"
source = "https://github.com/allista/AT_Utils.git"

[mods.AnisotropicPartResizer]
source_type = "git"
source = "https://github.com/allista/AnisotropicPartResizer.git"
depends = ["ModuleManager", "AT_Utils"]

[mods.ConfigurableContainers]
source_type = "git"
source = "https://github.com/allista/ConfigurableContainers.git"
depends = ["ModuleManager", "AT_Utils", "AnisotropicPartResizer"]

[mods.FireSpitterCore]
source_type = "git"
source = "https://github.com/snjo/Firespitter.git"
depends = ["ModuleManager"]

[mods.USI_Core]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/USI_Core.git"
depends = ["USITools", "CommunityResourcePack", "CommunityCategoryKit", "FireSpitterCore", "ModuleManager"]

[mods.MultiAnimators]
source_type = "git"
source = "https://github.com/allista/MultiAnimators.git"
depends = ["AT_Utils", "AnisotropicPartResizer"]

[mods.GroundConstruction]
source_type = "git"
source = "https://github.com/allista/GroundConstruction.git"
depends = ["AT_Utils", "ConfigurableContainers", "MultiAnimators", "ModuleManager"]

[mods.MKS]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/MKS.git"
depends = ["ModuleManager", "GroundConstruction", "USITools", "USI_Core", "FireSpitterCore"]

[mods.DynamicBatteryStorage]
source_type = "git"
source = "https://github.com/ChrisAdderley/DynamicBatteryStorage.git"

[mods.NearFutureElectrical]
source_type = "git"
source = "https://github.com/ChrisAdderley/NearFutureElectrical.git"
depends = ["ModuleManager", "B9PartSwitch", "CommunityResourcePack", "DynamicBatteryStorage"]