target_dir = "~/KSP"

[install]
base = "~/Downloads/ksp-linux-1.8.1.zip"
dlc1 = "~/Downloads/KSP-Making_History_Expansion-en-us-lin-1.8.1.zip"
dlc2 = "~/Downloads/KSP-Breaking_Ground_Expansion-en-us-lin-1.3.1.zip"

[mods.adopted]
source_type = "adopted"

[mods.ModuleManager]
source_type = "git"
source = "https://github.com/sarbian/ModuleManager.git"
branch = "master"

[mods.KOS]
source_type = "git"
source = "https://github.com/KSP-KOS/KOS.git"
branch = "master"

[mods.Kopernicus]
source_type = "git"
source = "https://github.com/Kopernicus/Kopernicus.git"
branch = "1.8"
enabled = true
patch = '''
--- a/src/Kopernicus/Constants/CompatibilityChecker.cs
+++ b/src/Kopernicus/Constants/CompatibilityChecker.cs
@@ -50,7 +50,7 @@ namespace Kopernicus.Constants
         // Compatible version
         internal const Int32 VERSION_MAJOR = 1;
         internal const Int32 VERSION_MINOR = 8;
-        internal const Int32 REVISION = 0;
+        internal const Int32 REVISION = 1;
         internal const Int32 KOPERNICUS = 903;
 
         public static Boolean IsCompatible()
'''

[mods.CustomBarnKit]
source_type = "git"
source = "https://github.com/sarbian/CustomBarnKit.git"

[mods.OPM]
source_type = "http"
source = "https://github.com/Galileo88/Outer-Planets-Mod/releases/download/${version}/Outer_Planets_Mod-${version}.zip"
version = "2.2.5"

[mods.KSPModFileLocalizer]
source_type = "git"
source = "https://github.com/Nils277/KSPModFileLocalizer.git"

[mods.PlanetaryBaseSystems]
source_type = "git"
source = "https://github.com/Nils277/KerbalPlanetaryBaseSystems.git"
enabled = true

[mods.B9PartSwitch]
source_type = "git"
source = "https://github.com/blowfishpro/B9PartSwitch.git"
enabled = true

[mods.NearFutureProps]
source_type = "git"
source="https://github.com/ChrisAdderley/NearFutureProps.git"
enabled = true
tag = "1.1.0"

[mods.StationPartsExpansionRedux]
source_type = "git"
source = "https://github.com/ChrisAdderley/StationPartsExpansionRedux.git"

[mods.KerbalAlarmClock]
source_type = "git"
source = "https://github.com/TriggerAu/KerbalAlarmClock.git"

[mods.CommunityCategoryKit]
source_type = "git"
source = "https://github.com/BobPalmer/CommunityCategoryKit.git"

[mods.KSPDev_Utils]
source_type = "git"
source = "https://github.com/ihsoft/KSPDev_Utils.git"

[mods.KIS]
source_type = "git"
source = "https://github.com/ihsoft/KIS.git"

[mods.KAS]
source_type = "git"
source = "https://github.com/ihsoft/KAS.git"

[mods.DockRotate]
source_type = "git"
source = "https://github.com/peteletroll/DockRotate.git"

[mods.KerbalEngineer]
source_type = "git"
source = "https://github.com/jrbudda/KerbalEngineer.git"

[mods.CommunityTechTree]
source_type = "git"
source = "https://github.com/ChrisAdderley/CommunityTechTree.git"

[mods.CommunityResourcePack]
source_type = "git"
source = "https://github.com/BobPalmer/CommunityResourcePack.git"

[mods.USITools]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries.git"

[mods.USI_LS]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/USI-LS.git"

[mods.Konstruction]
source_type = "git"
source = "https://github.com/BobPalmer/Konstruction.git"

[mods.SCANsat]
source_type = "git"
source = "https://github.com/S-C-A-N/SCANsat.git"
branch = "release"

[mods.EnvironmentalVisualEnhancements]
source_type = "http"
source = "https://github.com/WazWaz/EnvironmentalVisualEnhancements/releases/download/EVE-1.8.0-2/EnvironmentalVisualEnhancements-${version}.zip"
version = "1.8.0.2"
enabled = false

[mods.StockVisualEnhancements]
source_type = "http"
source = "https://github.com/Galileo88/StockVisualEnhancements/releases/download/v${version}/SVE.v${version}.zip"
version = "1.4.1"
enabled = false

[mods.StockVisualEnhancements_HighRes]
source_type = "http"
source = "https://github.com/Galileo88/StockVisualEnhancements/releases/download/${version}/SVE_HighResTextures.zip"
version = "1.0.8"
enabled = false

[mods.scatterer]
source_type = "http"
source = "https://github.com/LGhassen/Scatterer/releases/download/0.0331b/scatterer-v0.0331b.zip"
enabled = false

[mods.X_Science]
source_type = "git"
source = "https://github.com/Flupster/KSP-X-Science"

[mods.ClickThroughBlocker]
source_type = "git"
source = "https://github.com/linuxgurugamer/ClickThroughBlocker.git"

[mods.ToolbarControl]
source_type = "git"
source = "https://github.com/linuxgurugamer/ToolbarControl.git"

[mods.KronalVesselViewer]
source_type = "git"
source = "https://github.com/linuxgurugamer/KronalVesselViewer.git"
patch = '''
--- a/KronalVesselViewer/VesselViewConfig.cs
+++ b/KronalVesselViewer/VesselViewConfig.cs
@@ -1,14 +1,10 @@
 ﻿
-#define KERAMZIT
-#define KAS
-
 using System;
 using System.Collections.Generic;
 using System.Reflection;
 using System.Linq;
 using System.Text;
 using UnityEngine;
-using KAS;
 
 using ProceduralFairings;
 '''

[mods.IndicatorLights]
source_type = "git"
source = "https://github.com/KSPSnark/IndicatorLights.git"

[mods.AT_Utils]
source_type = "git"
source = "https://github.com/allista/AT_Utils.git"

[mods.AnisotropicPartResizer]
source_type = "git"
source = "https://github.com/allista/AnisotropicPartResizer.git"

[mods.ConfigurableContainers]
source_type = "git"
source = "https://github.com/allista/ConfigurableContainers.git"

[mods.FireSpitterCore]
source_type = "git"
source = "https://github.com/snjo/Firespitter.git"

[mods.USI_Core]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/USI_Core.git"

[mods.MultiAnimators]
source_type = "git"
source = "https://github.com/allista/MultiAnimators.git"

[mods.GroundConstruction]
source_type = "git"
source = "https://github.com/allista/GroundConstruction.git"

[mods.MKS]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/MKS.git"

[mods.DynamicBatteryStorage]
source_type = "git"
source = "https://github.com/ChrisAdderley/DynamicBatteryStorage.git"
branch = "dev"
patchFile = "patches/DynamicBatteryStorage.patch"

[mods.NearFutureElectrical]
source_type = "git"
source = "https://github.com/ChrisAdderley/NearFutureElectrical.git"

[mods.NearFuturePropulsion]
source_type = "git"
source = "https://github.com/ChrisAdderley/NearFuturePropulsion.git"

[mods.NearFutureSolar]
source_type = "git"
source = "https://github.com/ChrisAdderley/NearFutureSolar.git"

[mods.NearFutureAeronautics]
source_type = "git"
source = "https://github.com/ChrisAdderley/NearFutureAeronautics.git"

[mods.NearFutureConstruction]
source_type = "git"
source = "https://github.com/ChrisAdderley/NearFutureConstruction.git"
enabled = false

[mods.NearFutureLaunchVehicles]
source_type = "git"
source = "https://github.com/ChrisAdderley/NearFutureLaunchVehicles.git"

[mods.KerbalActuators]
source_type = "git"
source = "https://github.com/Angel-125/KerbalActuators.git"

[mods.DeployableEngines]
source_type = "git"
source = "https://github.com/ChrisAdderley/DeployableEngines.git"

[mods.FilterExtension]
source_type = "git"
source = "https://github.com/linuxgurugamer/FilterExtension.git"
enabled = false

[mods.KramaxPluginReload]
source_type = "git"
source = "https://github.com/linuxgurugamer/KramaxPluginReload.git"
enabled = false

[mods.HyperEdit]
source_type = "git"
source = "https://github.com/Ezriilc/HyperEdit.git"
enabled = false

[mods.OSEWorkshop]
source_type = "git"
source = "https://github.com/linuxgurugamer/Workshop.git"

[mods.KramaxAutoPilot]
source_type = "git"
source = "https://github.com/linuxgurugamer/KramaxAutoPilot.git"
enabled = false

[mods.KSPRescuePodFix]
source_type = "git"
source = "https://github.com/shadowmage45/KSPRescuePodFix.git"

[mods.WorldStabilizer]
source_type = "git"
source = "https://github.com/whale2/WorldStabilizer.git"
enabled = false

[mods.FTT]
source_type = "git"
source = "https://github.com/BobPalmer/FTT.git"

[mods.RasterPropMonitor]
source_type = "git"
source = "https://github.com/Mihara/RasterPropMonitor.git"
enabled = false

[mods.DockingPortAlignmentIndicator]
source_type = "git"
source = "https://github.com/mwerle/DockingPortAlignmentIndicator.git"
enabled = false

[mods.NavInstruments]
source_type = "git"
source = "https://github.com/net-lisias-kspu/NavInstruments.git"
enabled = false

[mods.DistantObject]
source_type = "git"
source = "https://github.com/MOARdV/DistantObject.git"
enabled = false

[mods.CustomAsteroids]
source_type = "git"
source = "https://github.com/Starstrider42/Custom-Asteroids.git"
enabled = false

[mods.SpaceTuxLibrary]
source_type = "git"
source = "https://github.com/linuxgurugamer/SpaceTuxLibrary.git"
