target_dir = "~/KSP"

[install]
base = "~/Downloads/ksp-linux-1.5.1.zip"
dlc1 = "~/Downloads/KSP-Making_History_Expansion-en-us-lin-1.5.1.zip"

[mods.adopted]
source_type = "adopted"
depends = ["KOS"]

[mods.ModuleManager]
source_type = "git"
source = "https://github.com/sarbian/ModuleManager.git"
branch = "master"

[mods.KOS]
source_type = "git"
source = "https://github.com/KSP-KOS/KOS.git"
branch = "master"
depends = ["ModuleManager"]

[mods.Kopernicus]
source_type = "git"
source = "https://github.com/Kopernicus/Kopernicus.git"
tag = "release-1.5.1-1"
enabled = true

[mods.CustomBarnKit]
source_type = "git"
source = "https://github.com/sarbian/CustomBarnKit.git"

[mods.OPM]
source_type = "http"
source = "https://github.com/Galileo88/Outer-Planets-Mod/releases/download/${version}/Outer_Planets_Mod-${version}.zip"
version = "2.2.1"
depends = ["Kopernicus"]

[mods.PlanetaryBaseSystems]
source_type = "git"
source = "https://github.com/Nils277/KerbalPlanetaryBaseSystems.git"
enabled = false
depends = ["ModuleManager"]

[mods.B9PartSwitch]
source_type = "git"
source = "https://github.com/blowfishpro/B9PartSwitch.git"
depends = ["ModuleManager"]
enabled = false

[mods.NearFutureProps]
source_type = "git"
source="https://github.com/ChrisAdderley/NearFutureProps.git"
depends = ["ModuleManager"]
enabled = false

[mods.StationPartsExpansionRedux]
source_type = "git"
source = "https://github.com/ChrisAdderley/StationPartsExpansionRedux.git"
depends = ["ModuleManager", "B9PartSwitch", "NearFutureProps"]

[mods.KerbalAlarmClock]
source_type = "git"
source = "https://github.com/TriggerAu/KerbalAlarmClock.git"

[mods.CommunityCategoryKit]
source_type = "git"
source = "https://github.com/BobPalmer/CommunityCategoryKit.git"

[mods.KSPDev]
source_type = "git"
source = "https://github.com/ihsoft/KSPDev.git"

[mods.KIS]
source_type = "git"
source = "https://github.com/ihsoft/KIS.git"
depends = ["CommunityCategoryKit", "KSPDev"]

[mods.KAS]
source_type = "git"
source = "https://github.com/ihsoft/KAS.git"
depends = ["CommunityCategoryKit", "KSPDev"]

[mods.DockRotate]
source_type = "git"
source = "https://github.com/peteletroll/DockRotate.git"
enabled = false

[mods.Konstruction]
source_type = "git"
source = "https://github.com/BobPalmer/Konstruction.git"
enabled = false

[mods.KerbalEngineer]
source_type = "git"
source = "https://github.com/jrbudda/KerbalEngineer.git"

[mods.CommunityTechTree]
source_type = "git"
source = "https://github.com/ChrisAdderley/CommunityTechTree.git"

[mods.CommunityResourcePack]
source_type = "git"
source = "https://github.com/BobPalmer/CommunityResourcePack.git"

[mods.USITools]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries.git"

[mods.USI_LS]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/USI-LS.git"
depends = ["CommunityCategoryKit", "CommunityResourcePack", "USITools"]
patch = '''
--- a/Source/USILifeSupport/LifeSupportMonitor.cs
+++ b/Source/USILifeSupport/LifeSupportMonitor.cs
@@ -1,7 +1,6 @@
 ﻿using System;
 using System.CodeDom;
 using System.Collections.Generic;
-using System.Data.SqlTypes;
 using System.IO;
 using System.Linq;
 using System.Reflection;
'''

[mods.SCANsat]
source_type = "git"
source = "https://github.com/S-C-A-N/SCANsat.git"
branch = "release"