target_dir = "~/KSP"

[install]
base = "~/Downloads/ksp-linux-1.5.1.zip"
dlc1 = "~/Downloads/KSP-Making_History_Expansion-en-us-lin-1.5.1.zip"

[mods.adopted]
source_type = "adopted"
depends = ["KOS"]

[mods.ModuleManager]
source_type = "git"
source = "https://github.com/sarbian/ModuleManager.git"
branch = "master"

[mods.KOS]
source_type = "git"
source = "https://github.com/KSP-KOS/KOS.git"
branch = "master"
depends = ["ModuleManager"]

[mods.Kopernicus]
source_type = "git"
source = "https://github.com/Kopernicus/Kopernicus.git"
tag = "release-1.5.0-1"
enabled = true
patch = '''
--- a/src/Kopernicus/Constants/CompatibilityChecker.cs
+++ b/src/Kopernicus/Constants/CompatibilityChecker.cs
@@ -49,7 +49,7 @@ namespace Kopernicus
         // Compatible version
         internal const Int32 version_major = 1;
         internal const Int32 version_minor = 5;
-        internal const Int32 Revision = 0;
+        internal const Int32 Revision = 1;
         internal const Int32 Kopernicus = 1;
 
         public static Boolean IsCompatible()
'''

[mods.CustomBarnKit]
source_type = "git"
source = "https://github.com/sarbian/CustomBarnKit.git"

[mods.OPM]
source_type = "http"
source = "https://github.com/Galileo88/Outer-Planets-Mod/releases/download/${version}/Outer_Planets_Mod-${version}.zip"
version = "2.2.1"
depends = ["Kopernicus"]

[mods.PlanetaryBaseSystems]
source_type = "git"
source = "https://github.com/Nils277/KerbalPlanetaryBaseSystems.git"
enabled = false
depends = ["ModuleManager"]

[mods.B9PartSwitch]
source_type = "git"
source = "https://github.com/blowfishpro/B9PartSwitch.git"
depends = ["ModuleManager"]
enabled = false

[mods.NearFutureProps]
source_type = "git"
source="https://github.com/ChrisAdderley/NearFutureProps.git"
depends = ["ModuleManager"]
enabled = false

[mods.StationPartsExpansionRedux]
source_type = "git"
source = "https://github.com/ChrisAdderley/StationPartsExpansionRedux.git"
depends = ["ModuleManager", "B9PartSwitch", "NearFutureProps"]

[mods.KerbalAlarmClock]
source_type = "git"
source = "https://github.com/TriggerAu/KerbalAlarmClock.git"

[mods.CommunityCategoryKit]
source_type = "git"
source = "https://github.com/BobPalmer/CommunityCategoryKit.git"

[mods.KSPDev]
source_type = "git"
source = "https://github.com/ihsoft/KSPDev.git"

[mods.KIS]
source_type = "git"
source = "https://github.com/ihsoft/KIS.git"
depends = ["CommunityCategoryKit", "KSPDev"]

[mods.KAS]
source_type = "git"
source = "https://github.com/ihsoft/KAS.git"
enabled = false
depends = ["CommunityCategoryKit", "KSPDev"]

[mods.DockRotate]
source_type = "git"
source = "https://github.com/peteletroll/DockRotate.git"
enabled = false

[mods.Konstruction]
source_type = "git"
source = "https://github.com/BobPalmer/Konstruction.git"
enabled = false

[mods.KerbalEngineer]
source_type = "git"
source = "https://github.com/jrbudda/KerbalEngineer.git"
patch = '''
--- a/KerbalEngineer/KerbalEngineer.csproj
+++ b/KerbalEngineer/KerbalEngineer.csproj
@@ -91,7 +91,7 @@
     <Compile Include="Flight\Readouts\Orbital\MeanAnomaly.cs" />
     <Compile Include="Flight\Readouts\Orbital\EccentricAnomaly.cs" />
     <Compile Include="Flight\Readouts\Orbital\ArgumentOfPeriapsis.cs" />
-    <Compile Include="Flight\Readouts\Orbital\CurrentSoi.cs" />
+    <Compile Include="Flight\Readouts\Body\CurrentSoi.cs" />
     <Compile Include="Flight\Readouts\Orbital\SemiMajorAxis.cs">
       <SubType>Code</SubType>
     </Compile>
@@ -162,7 +162,6 @@
     <Compile Include="Flight\Readouts\Vessel\SimulationProcessor.cs" />
     <Compile Include="Flight\Readouts\Vessel\Acceleration.cs" />
     <Compile Include="Flight\Presets\PresetLibrary.cs" />
-    <Compile Include="Flight\Readouts\Vessel\SuicideBurnProcessor.cs" />
     <Compile Include="Flight\Readouts\Vessel\SurfaceThrustToWeight.cs" />
     <Compile Include="Flight\Readouts\Surface\Situation.cs" />
     <Compile Include="Flight\Readouts\Vessel\ThrustOffsetAngle.cs" />
@@ -185,7 +184,8 @@
     <Compile Include="TrackingStation\SectionEditorTS.cs" />
     <Compile Include="TrackingStation\SectionModuleTS.cs" />
     <Compile Include="TrackingStation\TrackingStationAppLauncher.cs" />
-    <Compile Include="UIControls\DropDown.cs" />
+    <Compile Include="UIControls\PopOutColorPicker.cs" />
+    <Compile Include="UIControls\PopOutElement.cs" />
     <Compile Include="MyLogger.cs" />
     <Compile Include="EngineerGlobals.cs" />
     <Compile Include="Extensions\DoubleExtensions.cs" />
@@ -257,7 +257,6 @@
     <Compile Include="Settings\SettingItem.cs" />
     <Compile Include="TapeDriveAnimator.cs" />
     <Compile Include="KeyBinding\KeyBindPopup.cs" />
-    <Compile Include="UIControls\WindowObject.cs" />
     <Compile Include="VesselSimulator\AttachNodeSim.cs" />
     <Compile Include="VesselSimulator\EngineSim.cs" />
     <Compile Include="Helpers\Pool.cs" />
@@ -267,6 +266,23 @@
     <Compile Include="VesselSimulator\SimManager.cs" />
     <Compile Include="VesselSimulator\Simulation.cs" />
     <Compile Include="VesselSimulator\Stage.cs" />
+    <Compile Include="Flight/Readouts/Orbital/ManoeuvreNode/PostBurnRelativeInclination.cs"/>
+    <Compile Include="Drawing/DebugDrawing.cs"/>
+    <Compile Include="Flight/Readouts/ReadoutModuleConfigNode.cs"/>
+    <Compile Include="Flight/Readouts/Miscellaneous/ClearSeparator.cs"/>
+    <Compile Include="Flight/Readouts/Body/Gravity.cs"/>
+    <Compile Include="Flight/Readouts/Body/BodyRadius.cs"/>
+    <Compile Include="Flight/Readouts/Body/Mass.cs"/>
+    <Compile Include="Flight/Readouts/Body/EscapeVelocity.cs"/>
+    <Compile Include="Flight/Readouts/Body/RotationPeriod.cs"/>
+    <Compile Include="Flight/Readouts/Body/OrbitalPeriod.cs"/>
+    <Compile Include="Flight/Readouts/Body/GeostationaryHeight.cs"/>
+    <Compile Include="Flight/Readouts/Body/MinOrbitHeight.cs"/>
+    <Compile Include="Flight/Readouts/Vessel/SuicideBurnLength.cs"/>
+    <Compile Include="Flight/Readouts/Vessel/SuicideBurnCountdown.cs"/>
+    <Compile Include="Flight/Readouts/Vessel/Gravity.cs"/>
+    <Compile Include="Flight/Readouts/Surface/ImpactMarker.cs"/>
+    <Compile Include="Flight/Readouts/Orbital/ManoeuvreNode/PostBurnEccentricity.cs"/>
   </ItemGroup>
   <ItemGroup>
     <Reference Include="Assembly-CSharp">
'''

[mods.CommunityTechTree]
source_type = "git"
source = "https://github.com/ChrisAdderley/CommunityTechTree.git"

[mods.CommunityResourcePack]
source_type = "git"
source = "https://github.com/BobPalmer/CommunityResourcePack.git"

[mods.USITools]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries.git"
enabled = false

[mods.USI_LS]
source_type = "git"
source = "https://github.com/UmbraSpaceIndustries/USI-LS.git"
enabled = false
depends = ["CommunityCategoryKit", "CommunityResourcePack", "USITools"]
